/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.akorolev.forms;

/**
 *
 * @author alex
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuManagment = new javax.swing.JMenu();
        jMenuAnalis = new javax.swing.JMenu();
        jMenuService = new javax.swing.JMenu();
        jMenuAdvantures = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuManagment.setText("Управление");
        jMenuBar1.add(jMenuManagment);

        jMenuAnalis.setText("Аналитика");
        jMenuBar1.add(jMenuAnalis);

        jMenuService.setText("Сервис");
        jMenuBar1.add(jMenuService);

        jMenuAdvantures.setText("Дополнительно");
        jMenuBar1.add(jMenuAdvantures);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAdvantures;
    private javax.swing.JMenu jMenuAnalis;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuManagment;
    private javax.swing.JMenu jMenuService;
    // End of variables declaration//GEN-END:variables
}
